spring.application.name=BlueWave
# tamanho máximo de um único arquivo
spring.servlet.multipart.max-file-size=10MB

# tamanho máximo de toda a requisição (vários arquivos + campos)
spring.servlet.multipart.max-request-size=10MB

logging.level.org.thymeleaf=DEBUG
logging.level.org.springframework.web=DEBUG
# Permitir acesso aos arquivos uploadados
spring.web.resources.static-locations=classpath:/static/,file:${user.dir}/uploads/