# Application name
spring.application.name=BlueWave

# Multipart configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Logging
logging.level.org.thymeleaf=DEBUG
logging.level.org.springframework.web=DEBUG

# Static resources
spring.web.resources.static-locations=classpath:/static/,file:${user.dir}/uploads/

# Email configuration - CORRIGIDA
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bluwavecurso@gmail.com
# IMPORTANTE: Remova os espaços da senha de app do Gmail
spring.mail.password=qzmmjmsrjpoydrms
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.debug=true

# App name
app.name=Blue Wave